name: Player Initialization

on:
  workflow_dispatch:
    inputs:
      displayName:
        description: 'The display name of the player'
        required: true
        default: ''
      tag:
        description: 'The tag of the player'
        required: true
        default: ''
      region:
        description: 'The region of the player'
        required: true
        default: ''

run-name: "Adding ${{ inputs.region }} user: ${{ inputs.displayName }}#${{ inputs.tag }}"

jobs:
  init_player:
    runs-on: ubuntu-latest

    environment: Prod
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/actions/requirements.txt

      - name: Run initialization script
        env:
            RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
            MONGO_URI: ${{ secrets.MONGO_URI }}
            WRAP_YEAR: ${{ vars.WRAP_YEAR }}
        run: python backend/actions/user_producer.py "${{ github.event.inputs.displayName }}" "${{ github.event.inputs.tag }}" "${{ github.event.inputs.region }}"
